BE2AspNetMvc/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using BE2AspNetMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BE2AspNetMvc.Controllers
{
    public class ProductsController : Controller
    {
        // GET: ProductsController
        public async Task<ActionResult> Index()
        {
            var http = new HttpClient();
            var products = await http.GetFromJsonAsync<List<Product>>("https://be1-webapi.azurewebsites.net/api/products");

            return View(products);
        }



        // GET: ProductsController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var http = new HttpClient();
            var product = await http.GetFromJsonAsync<Product>($"https://be1-webapi.azurewebsites.net/api/products/{id}");
            
            return View(product);
        }


        // GET: ProductsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Product product)
        {
            try
            {
                var client = new HttpClient();
                await client.PostAsJsonAsync("https://be1-webapi.azurewebsites.net/api/products", product);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: ProductsController/Edit/5
        public ActionResult Edit(int id)
        {

            return View();
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {

            try
            {
                var client = new HttpClient();
                await client.PutAsJsonAsync($"https://be1-webapi.azurewebsites.net/api/products/{id}", collection);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }

            
        }

        // GET: ProductsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BE2AspNetMvc/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using BE2AspNetMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BE2AspNetMvc.Controllers
{
    public class UsersController : Controller
    {
        // GET: UsersController
        public async Task<ActionResult> Index()
        {
            var http = new HttpClient();
            var users = await http.GetFromJsonAsync<List<User>>("https://be1-webapi.azurewebsites.net/api/users");

            return View(users);
        }

        // GET: UsersController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var http = new HttpClient();
            var user = await http.GetFromJsonAsync<User>($"https://be1-webapi.azurewebsites.net/api/users/{id}");

            return View(user);
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(User user)
        {
            try
            {
                var client = new HttpClient();
                await client.PostAsJsonAsync("https://be1-webapi.azurewebsites.net/api/users", user);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {

            try
            {
                var client = new HttpClient();
                await client.PutAsJsonAsync($"https://be1-webapi.azurewebsites.net/api/users/{id}", collection);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }


        }

        // GET: UsersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UsersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                var client = new HttpClient();
                await client.DeleteAsync($"https://be1-webapi.azurewebsites.net/api/users/{id}");

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BE2AspNetMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">

    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <title @ViewData["Title"]></title>


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fas fa-splotch"></i> Shoppen</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Hem</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Products" asp-action="Index">Produkter</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-controller="Products" asp-action="Create">Skapa produkt</a>
                    </li>

                </ul>

                <ul class="navbar-nav">
                    <li>
                        <a class="nav-link" asp-controller="Users" asp-action="Create">Registrera konto</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-controller="Users" asp-action="SignIn">Logga in</a>
                    </li>
                    <li class="nav-item dropdown me-3">
                        <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-shopping-cart"></i>
                            <span class="badge rounded-pill badge-notification bg-success">0</span>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-end shopping-cart" aria-labelledby="navbarDropdown">
                            <shopping-cart />
                        </ul>
                    </li>

                </ul>
                
                
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>